// Generated by sequelize-cli, modified to support use_env_variable.
//

'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(module.filename);
var env       = process.env.NODE_ENV || 'development';
var config    = require('../config/database.json')[env];
var db        = {};
var sequelize;

// sequelize-cli "use_env_variable" option processing...
//
if(config.use_env_variable){
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
}else{
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}

// This code is only executed at server startup,
// using sync here is ok.
//
fs.readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf('.') !== 0) && (file !== basename);
  })
  .forEach(function(file) {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ('associate' in db[modelName]) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
